version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: project-school
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
