version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: project-school
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  redis:
    image: bitnami/redis
    container_name: redis-project-school
    depends_on:
      - db
    ports:
      - REDIS_PORT:REDIS_PORT
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
